SELECT * FROM emp
WHERE hiredate < (SELECT hiredate
                    FROM emp
                    WHERE ename = 'SCOTT');
                    
SELECT hiredate FROM emp
                WHERE ename = 'SCOTT';
                
SELECT *
FROM EMP
WHERE hiredate < '19870419';

--//다중행 서브쿼리//--
SELECT * FROM EMP WHERE DEPTNO IN (20, 30);

SELECT * FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT * FROM emp WHERE sal < ANY(SELECT sal FROM emp WHERE DEPTNO = 30)
ORDER BY sal, empno;

SELECT SAL FROM EMP WHERE DEPTNO = 30;

SELECT * FROM EMP WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO = 10);

SELECT * FROM DEPT WHERE DEPTNO = 10;

SELECT * FROM DEPT;

--//인라인뷰//--
SELECT ROWNUM, ENAME, SAL FROM EMP;
SELECT ROWNUM, ENAME, SAL FROM EMP WHERE SAL > 1500;

SELECT ROWNUM, ENAME, HIREDATE FROM EMP ORDER BY HIREDATE DESC;

SELECT ROWNUM, ENAME, SAL FROM EMP WHERE ROWNUM > 5;﻿

SELECT ROWNUM, EMPNO, ENAME, HIREDATE FROM 
(SELECT * FROM EMP ORDER BY HIREDATE DESC) 
WHERE ROWNUM <= 5;

SELECT ROWNUM, RNUM, ENAME, SAL FROM 
(SELECT ROWNUM RNUM, ENAME, SAL FROM -- FROM 절의 INLINE VIEW ROWNUM에 대해 별칭 부여 
(SELECT * FROM EMP ORDER BY SAL DESC)) 
WHERE RNUM BETWEEN 6 AND 10;


CREATE TABLE A1(
    NO              NUMBER(3)      PRIMARY KEY,
    HIREDATE        DATE,
    BUSINESS_NAME   VARCHAR2(30),
    GOODS           VARCHAR2(25),
    NAME            VARCHAR2(35),
    QUANTITY        NUMBER(4, 0),
    PRICE           NUMBER(9),
    SUM             NUMBER(27)
);

SELECT * FROM A1;            

--정답--
CREATE TABLE PRODUCT (
    PWDAY DATE,
    GRCM CHAR(2),
    SPBR CHAR(8),
    PM   CHAR(2),
    CNT  INT,
    DG   INT
);

INSERT INTO PRODUCT VALUES('2021-07-02', 'gy', '노트', 'hs', 20, 25000);

SELECT * FROM PRODUCT;
SELECT PWDAY, GRCM, SPBR, PM, CNT, DG, CNT*DG AS 합계 FROM PRODUCT;

SELECT CNT*DG FROM PRODUCT;

select * from dept_tcl;

insert from dept_tcl VALES(50, 'DATABASE', 'SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

DELETE FROM 